### ISSUE TITLE
Does this work if spotify is installed by snap?

### ISSUE THREAD

**Issue by AwareSuperCC** [mihirlad55/polybar-spotify-module#18]
Im on arch-linux and for some reason whenever I download spotify from aur it crashes at launch. I can only open it if its downloaded with snap. So will this module work if spotify is installed by snap?

**Comment by mihirlad55** [comment]
Sorry for the delayed response, I've been busy with school. I'm not sure if it will work. I'm not too familiar with how snap interacts with D-Bus. No harm in trying it out to see if it works. If it doesn't, I can try doing some more research to see if it's possible for the module to work with snap.

**Comment by mihirlad55** [comment]
Since there has been no response, I will close this issue. If you are interested in still trying spotify with snap, I can re-open this issue and do a bit of research to see if it's possible, though I believe this is more of a spotify-snap issue then a module issue.
