### ISSUE TITLE
Status formatting options

### ISSUE THREAD

**Issue by mihirlad55** [mihirlad55/polybar-spotify-module#8]
Add commandline options for formatting status output.

**Comment by Rayqan** [comment]
Any progress made on this issue?

**Comment by mihirlad55** [comment]
Hey, sorry I got caught up with finals and this kinda slipped my mind. No progress yet.

Anyways, I'll try to put in some work this week. If you have any specific suggestions on what options you'd like to see, I can take them into consideration when developing this feature.

**Comment by Rayqan** [comment]
Nothing really specific, only thing I would say is to add an option to truncate strings exceeding a given length.

**Comment by mihirlad55** [comment]
Ok, I'm planning to add options to specify the format and max length of the track and artist. Specifically the following:
- Max length of artist
- Max length of track title
- Max length of overall output

In terms of specifying the command, maybe something along the lines of:
```
spotifyctl status \
    --format "%artist%: %title%" \
    --max-artist-length 15 \
    --max-title-length 10 \
    --max-length 20
```

By the way, there is some logic to specify these lengths hardcoded in the program if you would like to re-compile it with your own specific lengths while I work on the feature:
https://github.com/mihirlad55/polybar-spotify-module/blob/master/src/spotifyctl.c#L27

**Comment by Rayqan** [comment]
Got it, will definitely look into recompiling.

**Comment by mihirlad55** [comment]
The feature is almost ready. I'm just organizing them into separate commits right now. Unfortunately, there seems to be some minor memory leaks caused by the new feature which I will have to look into, but I should have at least a working version up within the hour if you would like to test it.

**Comment by mihirlad55** [comment]
Okay, its all been pushed:
https://github.com/mihirlad55/polybar-spotify-module/tree/feature-status-formatting

Main feature related commits:
- 2b9668554a748766a0ee73f41c5e265bc93b46aa
- a68599e21ab0383017670fdaa7379308a52fe559
- cea8a6f2229f3a46f6e4464a1c49eebcc572f002
- 06a8c8ed750a444a0908460f9ea9d75f69a4e042

After I fix the memory leaks and do some quick testing, I will make an official release and push this to master.

**Comment by mihirlad55** [comment]
Some more commits were just added. If max length is specified, artist and title will not be truncated if the entire output satisfies the max length constraint.
